name: Monitor

on:
  push:

jobs:
  urls_monitor:
    name: URLs Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Check an URL
        run: |
          code=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' ${{secrets.SECRET_URL}})
          if [ "$code" -eq 401 ]; then
            exit 0
          else
            exit 1
          fi
