name: Monitor

on:
  workflow_dispatch:
  push:

jobs:
  urls_monitor:
    name: URLs Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: janekmi/private_urls
          token: ${{ secrets.PRIVATE_URLS_PAT }}
      - name: Check an URL
        run: ./process.sh
