name: Monitor

on:
  push:

jobs:
  urls_monitor:
    name: URLs Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: janekmi/private_urls
          token: ${{ secrets.PRIVATE_URLS_PAT }}
      - name: Check an URL
        run: |
          echo "::add-mask::kulik.txt"
          IFS=',' read -r -a values < kulik.txt
          for value in "${values[@]}"; do
            echo "Processing: $value"
          done

# code=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' ${{secrets.SECRET_URL}})
# [ "$code" -eq 401 ]
